### PR TITLE
fixed tests

### PR DESCRIPTION
**Pull request by danrot**
This PR is trying to fix the tests in husky. It already works quite well, there is just one flaky test (the password field) and one failing for the tabs, which I have skipped for now.

The SmartContent component has been move to Sulu, so I also removed all tests and demos regarding this component.

**tasks:**
- [ ] gather feedback for my changes

**informations:**

| q | a |
| --- | --- |
| Fixed tickets | none |
| BC breaks | none |
| Documentation PR | none |

### CODE REVIEW

**Comment by danrot** [comment]
Some tests are still failing for PhantomJS, and it seems to me like this is the only browser you can use for tests on travis...

**Comment by wachterjohannes** [comment]
when you run them locally with phantom? did they fail?

**Comment by danrot** [comment]
Yeah, they also fail locally with phantomjs

**Comment by danrot** [comment]
The entire frontend will be refactored anyway, so I am closing this.

**Pull request closed without merging**
