### PR TITLE
Issue when using addPlugin method of ckeditor extension

### PR DESCRIPTION
**Pull request by SarramegnaG**
Fix issue when using addPlugin method of ckeditor extension without passing a plugin parameter.

Related issue : https://github.com/sulu/sulu/issues/3313

### CODE REVIEW

**Comment by alexander-schranz** [comment]
@SarramegnaG you need to create the build locally for this you need `npm` and `grunt`.

When I remember it correctly when you then run following commands:

```
npm install
grunt build
```

The dist/husky.js and dist/husky.min.js  should be builded.

**Comment by SarramegnaG** [comment]
Sorry I thought the part with all the command lines was to install, not to contribute.

I updated with dist files. It should be ok now :)

**Comment by wachterjohannes** [comment]
@SarramegnaG sorry for the long delay (: can you also add a line to `CHANGELOG.md`

**Comment by wachterjohannes** [comment]
replaced by https://github.com/massiveart/husky/pull/770

**Pull request closed without merging**
